/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dbms.eat;

import Class.Menu;
import Class.Restaurant;
import Class.User;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adil
 */
public class CartGUI extends javax.swing.JFrame {

    RestaurantGUI rg;
    User u = new User();
    Restaurant r;
    ArrayList<String> aList;

    public CartGUI() {
        initComponents();
    }

    public CartGUI(RestaurantGUI rg, User u, Restaurant r) {
        initComponents();
        this.rg = rg;
        this.u = u;
        this.r = r;
        loadTable();
        setTotals();
        System.out.println(tblmenu.getRowCount());
        setComboBoxData();
    }

    public void setComboBoxData() {
        aList = u.getuAddressList();
        for (int i = 0; i < aList.size(); i++) {

            cbaddress.addItem(aList.get(i));
        }
        cbaddress.addItem("Add new address");
    }

    public void loadTable() {
        lblrname.setText(rg.getLblrname());
        lblradd.setText(rg.getLblradd());
        DefaultTableModel model1 = (DefaultTableModel) tblmenu.getModel();

        for (int i = 0; i < rg.mList.size(); i++) {
            Menu mobj;
            mobj = rg.mList.get(i);
            if (mobj.getQty() != 0) {
                model1.addRow(new Object[]{mobj.getQty(), mobj.getiName(), mobj.getiPrice(), mobj.getItemSubTotal()});
            }
        }
    }

    public ArrayList<Menu> getCartItems() {
        ArrayList<Menu> cartItems = new ArrayList<>();
        int column = 0;
        int row = 0;
        Menu m = new Menu();
        for (int i = 0; i < tblmenu.getRowCount(); i++) {

            row = i;
            m.setQty(Integer.parseInt(tblmenu.getModel().getValueAt(row, 0).toString()));
            m.setiName((tblmenu.getModel().getValueAt(row, 1).toString()));
            m.setiPrice(Float.parseFloat(tblmenu.getModel().getValueAt(row, 1).toString()));
            m.setItemSubTotal(Float.parseFloat(tblmenu.getModel().getValueAt(row, 1).toString()));
            cartItems.add(m);
        }
        return cartItems;
    }

    public void setTotals() {
        float subTotal = 0;
        float Total = 0;
        for (int i = 0; i < rg.mList.size(); i++) {
            Menu mobj;
            mobj = rg.mList.get(i);
            if (mobj.getQty() != 0) {
                subTotal += mobj.getItemSubTotal();
            }
        }
        Total = subTotal - Float.parseFloat(lbldiscount.getText());
        lblsubtotal.setText(String.valueOf(subTotal));
        lbltotal.setText(String.valueOf(Total));
    }

    public JLabel getLblccode() {
        return lblccode;
    }

    public void setLblccode(String lblccode) {
        this.lblccode.setText(lblccode);
    }

    public void setLbldiscount(String discount) {
        this.lbldiscount.setText(discount);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbltotal = new javax.swing.JLabel();
        lblsubtotal = new javax.swing.JLabel();
        lblrname = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnapplycoupon = new javax.swing.JButton();
        cbpmethod = new javax.swing.JComboBox<>();
        btnplaceorder = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        lblccode = new javax.swing.JLabel();
        lblradd = new javax.swing.JLabel();
        jlabel = new javax.swing.JLabel();
        lbldiscount = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblmenu = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cbaddress = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setPreferredSize(new java.awt.Dimension(1366, 766));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 51, 51));
        jLabel18.setText("Total");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Subtotal");

        lbltotal.setText("0");

        lblsubtotal.setText("0");

        lblrname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblrname.setText("Restaurant Name");

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setText("Add more items");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnapplycoupon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnapplycoupon.setForeground(new java.awt.Color(255, 51, 51));
        btnapplycoupon.setText("Apply a coupon");
        btnapplycoupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnapplycouponActionPerformed(evt);
            }
        });

        cbpmethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Card" }));

        btnplaceorder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnplaceorder.setForeground(new java.awt.Color(255, 51, 51));
        btnplaceorder.setText("Place Order");
        btnplaceorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplaceorderActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 51, 51));
        jLabel19.setText("Payment Method");

        lblccode.setText("N/A");

        lblradd.setText("Restaurant Address");

        jlabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlabel.setForeground(new java.awt.Color(255, 51, 51));
        jlabel.setText("Discount");

        lbldiscount.setText("0");

        tblmenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Qty", "Menu Item", "Item Price", "ItemSubTotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tblmenu);

        jLabel2.setText("PIC");

        cbaddress.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbaddressItemStateChanged(evt);
            }
        });
        cbaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbaddressActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Delivery Address");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/eat/logo.jpg"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("MY CART");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dbms/eat/addtocart.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(20, 20, 20))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblrname, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblradd, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 190, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(btnplaceorder)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(btnapplycoupon)
                                    .addComponent(jlabel)
                                    .addComponent(jLabel19)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(111, 111, 111)
                                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbpmethod, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbldiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblccode, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(80, 80, 80))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5)))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblrname)
                        .addGap(18, 18, 18)
                        .addComponent(lblradd))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblsubtotal))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnapplycoupon)
                            .addComponent(lblccode))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlabel)
                            .addComponent(lbldiscount))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(cbpmethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(lbltotal))
                        .addGap(25, 25, 25)
                        .addComponent(btnplaceorder))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jButton1))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 602, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnapplycouponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnapplycouponActionPerformed
        CouponGUI cgui = new CouponGUI(this, u);
        cgui.setVisible(true);
        setTotals();
    }//GEN-LAST:event_btnapplycouponActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        rg.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbaddressActionPerformed

    private void cbaddressItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbaddressItemStateChanged
        if (cbaddress.getSelectedItem().toString().equals("Add new address")) {
            cbaddress.getItemCount();
            cbaddress.removeItemAt(cbaddress.getItemCount() - 1);
            String v = JOptionPane.showInputDialog(null, "Enter new Address to deliver");
            cbaddress.addItem(v);
            cbaddress.setSelectedItem(v);
            u.addUserAddress(u.getuEmail(), v);
            cbaddress.addItem("Add new address");

        }
    }//GEN-LAST:event_cbaddressItemStateChanged

    private void btnplaceorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplaceorderActionPerformed
        u.placeOrder(lblccode.getText());
        int row;
        for (int i = 0; i < tblmenu.getRowCount(); i++) {
            String mn, qty, price, subtotal;
            row = i;
            qty = tblmenu.getModel().getValueAt(row, 0).toString();
            mn = tblmenu.getModel().getValueAt(row, 1).toString();
            price = tblmenu.getModel().getValueAt(row, 2).toString();
            subtotal = tblmenu.getModel().getValueAt(row, 3).toString();
            u.placeItemOrder(mn, Float.valueOf(price), Integer.parseInt(qty),
                    Float.valueOf(subtotal));
        }
        u.confirmCartOrder(cbaddress.getSelectedItem().toString(), lblrname.getText(), lblradd.getText(), u.getuEmail(),cbpmethod.getSelectedItem().toString());
    }//GEN-LAST:event_btnplaceorderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CartGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CartGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnapplycoupon;
    private javax.swing.JButton btnplaceorder;
    private javax.swing.JComboBox<String> cbaddress;
    private javax.swing.JComboBox<String> cbpmethod;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel lblccode;
    private javax.swing.JLabel lbldiscount;
    private javax.swing.JLabel lblradd;
    private javax.swing.JLabel lblrname;
    private javax.swing.JLabel lblsubtotal;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JTable tblmenu;
    // End of variables declaration//GEN-END:variables
}
